// Code generated by "go-syncmap -output meta_data_map.gen.go -type metaDataMap<string,*metaData>"; DO NOT EDIT.

package metadata

import "sync"

func _() {
	// An "cannot convert metaDataMap literal (type metaDataMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(metaDataMap{})
}
func (m *metaDataMap) Store(key string, value *metaData) {
	(*sync.Map)(m).Store(key, value)
}

func (m *metaDataMap) LoadOrStore(key string, value *metaData) (*metaData, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*metaData), loaded
}

func (m *metaDataMap) Load(key string) (*metaData, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*metaData), ok
}

func (m *metaDataMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *metaDataMap) Range(f func(key string, value *metaData) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*metaData))
	})
}
