// Code generated by "go-syncmap -output nse_sync_map.gen.go -type NetworkServiceEndpointSyncMap<string,*github.com/networkservicemesh/api/pkg/api/registry.NetworkServiceEndpoint>"; DO NOT EDIT.

package memory

import (
	"sync"

	"github.com/networkservicemesh/api/pkg/api/registry"
)

func _() {
	// An "cannot convert NetworkServiceEndpointSyncMap literal (type NetworkServiceEndpointSyncMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(NetworkServiceEndpointSyncMap{})
}
func (m *NetworkServiceEndpointSyncMap) Store(key string, value *registry.NetworkServiceEndpoint) {
	(*sync.Map)(m).Store(key, value)
}

func (m *NetworkServiceEndpointSyncMap) LoadOrStore(key string, value *registry.NetworkServiceEndpoint) (*registry.NetworkServiceEndpoint, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*registry.NetworkServiceEndpoint), loaded
}

func (m *NetworkServiceEndpointSyncMap) Load(key string) (*registry.NetworkServiceEndpoint, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*registry.NetworkServiceEndpoint), ok
}

func (m *NetworkServiceEndpointSyncMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *NetworkServiceEndpointSyncMap) Range(f func(key string, value *registry.NetworkServiceEndpoint) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*registry.NetworkServiceEndpoint))
	})
}
