// Code generated by "go-syncmap -output per_endpoint_file_map.gen.go -type perEndpointFileMapMap<string,*perEndpointFileMap>"; DO NOT EDIT.

package recvfd

import "sync"

func _() {
	// An "cannot convert perEndpointFileMapMap literal (type perEndpointFileMapMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(perEndpointFileMapMap{})
}
func (m *perEndpointFileMapMap) Store(key string, value *perEndpointFileMap) {
	(*sync.Map)(m).Store(key, value)
}

func (m *perEndpointFileMapMap) LoadOrStore(key string, value *perEndpointFileMap) (*perEndpointFileMap, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*perEndpointFileMap), loaded
}

func (m *perEndpointFileMapMap) Load(key string) (*perEndpointFileMap, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*perEndpointFileMap), ok
}

func (m *perEndpointFileMapMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *perEndpointFileMapMap) Range(f func(key string, value *perEndpointFileMap) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*perEndpointFileMap))
	})
}
