// Code generated by "go-syncmap -output ns_sync_map.gen.go -type nsClientMap<string,*nsCacheEntry>"; DO NOT EDIT.

package connect

import "sync"

func _() {
	// An "cannot convert nsClientMap literal (type nsClientMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(nsClientMap{})
}
func (m *nsClientMap) Store(key string, value *nsCacheEntry) {
	(*sync.Map)(m).Store(key, value)
}

func (m *nsClientMap) LoadOrStore(key string, value *nsCacheEntry) (*nsCacheEntry, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*nsCacheEntry), loaded
}

func (m *nsClientMap) Load(key string) (*nsCacheEntry, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*nsCacheEntry), ok
}

func (m *nsClientMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *nsClientMap) Range(f func(key string, value *nsCacheEntry) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*nsCacheEntry))
	})
}
