// Code generated by "go-syncmap -output nse_sync_map.gen.go -type nseClientMap<string,*nseCacheEntry>"; DO NOT EDIT.

package connect

import "sync"

func _() {
	// An "cannot convert nseClientMap literal (type nseClientMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(nseClientMap{})
}
func (m *nseClientMap) Store(key string, value *nseCacheEntry) {
	(*sync.Map)(m).Store(key, value)
}

func (m *nseClientMap) LoadOrStore(key string, value *nseCacheEntry) (*nseCacheEntry, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*nseCacheEntry), loaded
}

func (m *nseClientMap) Load(key string) (*nseCacheEntry, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*nseCacheEntry), ok
}

func (m *nseClientMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *nseClientMap) Range(f func(key string, value *nseCacheEntry) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*nseCacheEntry))
	})
}
