// Code generated by "go-syncmap -output ns_sync_map.gen.go -type StringRegistryNetworkServiceMap<string,*github.com/networkservicemesh/api/pkg/api/registry.NetworkService>"; DO NOT EDIT.

package syncmap

import (
	"sync"

	"github.com/networkservicemesh/api/pkg/api/registry"
)

func _() {
	// An "cannot convert StringRegistryNetworkServiceMap literal (type StringRegistryNetworkServiceMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(StringRegistryNetworkServiceMap{})
}
func (m *StringRegistryNetworkServiceMap) Store(key string, value *registry.NetworkService) {
	(*sync.Map)(m).Store(key, value)
}

func (m *StringRegistryNetworkServiceMap) LoadOrStore(key string, value *registry.NetworkService) (*registry.NetworkService, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*registry.NetworkService), loaded
}

func (m *StringRegistryNetworkServiceMap) Load(key string) (*registry.NetworkService, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*registry.NetworkService), ok
}

func (m *StringRegistryNetworkServiceMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *StringRegistryNetworkServiceMap) Range(f func(key string, value *registry.NetworkService) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*registry.NetworkService))
	})
}
