// Code generated by "go-syncmap -output nsm_sync_map.gen.go -type StringRegistryNetworkServiceManagerMap<string,*github.com/networkservicemesh/api/pkg/api/registry.NetworkServiceManager>"; DO NOT EDIT.

package syncmap

import (
	"sync"

	"github.com/networkservicemesh/api/pkg/api/registry"
)

func _() {
	// An "cannot convert StringRegistryNetworkServiceManagerMap literal (type StringRegistryNetworkServiceManagerMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(StringRegistryNetworkServiceManagerMap{})
}
func (m *StringRegistryNetworkServiceManagerMap) Store(key string, value *registry.NetworkServiceManager) {
	(*sync.Map)(m).Store(key, value)
}

func (m *StringRegistryNetworkServiceManagerMap) LoadOrStore(key string, value *registry.NetworkServiceManager) (*registry.NetworkServiceManager, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*registry.NetworkServiceManager), loaded
}

func (m *StringRegistryNetworkServiceManagerMap) Load(key string) (*registry.NetworkServiceManager, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*registry.NetworkServiceManager), ok
}

func (m *StringRegistryNetworkServiceManagerMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *StringRegistryNetworkServiceManagerMap) Range(f func(key string, value *registry.NetworkServiceManager) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*registry.NetworkServiceManager))
	})
}
