// Code generated by "go-syncmap -output sync_map.gen.go -type Map<string,*github.com/networkservicemesh/api/pkg/api/registry.NetworkServiceEndpoint>"; DO NOT EDIT.

package interpose

import (
	"sync"

	"github.com/networkservicemesh/api/pkg/api/registry"
)

func _() {
	// An "cannot convert Map literal (type Map) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(Map{})
}
func (m *Map) Store(key string, value *registry.NetworkServiceEndpoint) {
	(*sync.Map)(m).Store(key, value)
}

func (m *Map) LoadOrStore(key string, value *registry.NetworkServiceEndpoint) (*registry.NetworkServiceEndpoint, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*registry.NetworkServiceEndpoint), loaded
}

func (m *Map) Load(key string) (*registry.NetworkServiceEndpoint, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*registry.NetworkServiceEndpoint), ok
}

func (m *Map) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *Map) Range(f func(key string, value *registry.NetworkServiceEndpoint) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*registry.NetworkServiceEndpoint))
	})
}
