// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package maphelper_test

import (
	"context"
	"sync"

	"github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata"
)

type _TestMapKeyType string

var _IntNil int

type testMapMetaDataHelper struct {
	m *sync.Map
}

func testMapMetaData(ctx context.Context, isClient bool) *testMapMetaDataHelper {
	return &testMapMetaDataHelper{
		m: metadata.Map(ctx, isClient),
	}
}

func (h *testMapMetaDataHelper) Store(key string, value int) {
	h.m.Store(_TestMapKeyType(key), value)
}

func (h *testMapMetaDataHelper) LoadOrStore(key string, value int) (int, bool) {
	raw, ok := h.m.LoadOrStore(_TestMapKeyType(key), value)
	return raw.(int), ok
}

func (h *testMapMetaDataHelper) Load(key string) (int, bool) {
	if raw, ok := h.m.Load(_TestMapKeyType(key)); ok {
		return raw.(int), true
	}
	return _IntNil, false
}

func (h *testMapMetaDataHelper) LoadAndDelete(key string) (int, bool) {
	if raw, ok := h.m.LoadAndDelete(_TestMapKeyType(key)); ok {
		return raw.(int), true
	}
	return _IntNil, false
}

func (h *testMapMetaDataHelper) Delete(key string) {
	h.m.Delete(_TestMapKeyType(key))
}
