// Code generated by "-output ctx_wrapper_map.gen.go -type ctxWrapperMap<string,*ctxWrapper> -output ctx_wrapper_map.gen.go -type ctxWrapperMap<string,*ctxWrapper>"; DO NOT EDIT.
package heal

import (
	"sync" // Used by sync.Map.
)

// Generate code that will fail if the constants change value.
func _() {
	// An "cannot convert ctxWrapperMap literal (type ctxWrapperMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(ctxWrapperMap{})
}

var _nil_ctxWrapperMap_ctxWrapper_value = func() (val *ctxWrapper) { return }()

// Load returns the value stored in the map for a key, or nil if no
// value is present.
// The ok result indicates whether value was found in the map.
func (m *ctxWrapperMap) Load(key string) (*ctxWrapper, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return _nil_ctxWrapperMap_ctxWrapper_value, ok
	}
	return value.(*ctxWrapper), ok
}

// Store sets the value for a key.
func (m *ctxWrapperMap) Store(key string, value *ctxWrapper) {
	(*sync.Map)(m).Store(key, value)
}

// LoadOrStore returns the existing value for the key if present.
// Otherwise, it stores and returns the given value.
// The loaded result is true if the value was loaded, false if stored.
func (m *ctxWrapperMap) LoadOrStore(key string, value *ctxWrapper) (*ctxWrapper, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return _nil_ctxWrapperMap_ctxWrapper_value, loaded
	}
	return actual.(*ctxWrapper), loaded
}

// LoadAndDelete deletes the value for a key, returning the previous value if any.
// The loaded result reports whether the key was present.
func (m *ctxWrapperMap) LoadAndDelete(key string) (value *ctxWrapper, loaded bool) {
	actual, loaded := (*sync.Map)(m).LoadAndDelete(key)
	if actual == nil {
		return _nil_ctxWrapperMap_ctxWrapper_value, loaded
	}
	return actual.(*ctxWrapper), loaded
}

// Delete deletes the value for a key.
func (m *ctxWrapperMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

// Range calls f sequentially for each key and value present in the map.
// If f returns false, range stops the iteration.
//
// Range does not necessarily correspond to any consistent snapshot of the Map's
// contents: no key will be visited more than once, but if the value for any key
// is stored or deleted concurrently, Range may reflect any mapping for that key
// from any point during the Range call.
//
// Range may be O(N) with the number of elements in the map even if f returns
// false after a constant number of calls.
func (m *ctxWrapperMap) Range(f func(key string, value *ctxWrapper) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*ctxWrapper))
	})
}
