// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package helper

import (
	"context"
	"sync"

	"github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata"
)

type _IntKeyType struct{}

type IntMetadataHelper struct {
	m *sync.Map
}

func IntMetadata(ctx context.Context, isClient bool) *IntMetadataHelper {
	return &IntMetadataHelper{
		m: metadata.Map(ctx, isClient),
	}
}

func (h *IntMetadataHelper) Store(value int) {
	h.m.Store(_IntKeyType{}, value)
}

func (h *IntMetadataHelper) LoadOrStore(value int) (int, bool) {
	raw, ok := h.m.LoadOrStore(_IntKeyType{}, value)
	return raw.(int), ok
}

func (h *IntMetadataHelper) Load() (int, bool) {
	if raw, ok := h.m.Load(_IntKeyType{}); ok {
		return raw.(int), true
	}
	return func() (v int) { return }(), false
}

func (h *IntMetadataHelper) LoadAndDelete() (int, bool) {
	if raw, ok := h.m.LoadAndDelete(_IntKeyType{}); ok {
		return raw.(int), true
	}
	return func() (v int) { return }(), false
}

func (h *IntMetadataHelper) Delete() {
	h.m.Delete(_IntKeyType{})
}
