// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package helper_test

import (
	"context"
	"sync"

	"github.com/networkservicemesh/sdk/pkg/networkservice/utils/metadata"
)

type _TestKeyType struct{}

var _IntNil int

type testMetaDataHelper struct {
	m *sync.Map
}

func testMetaData(ctx context.Context, isClient bool) *testMetaDataHelper {
	return &testMetaDataHelper{
		m: metadata.Map(ctx, isClient),
	}
}

func (h *testMetaDataHelper) Store(value int) {
	h.m.Store(_TestKeyType{}, value)
}

func (h *testMetaDataHelper) LoadOrStore(value int) (int, bool) {
	raw, ok := h.m.LoadOrStore(_TestKeyType{}, value)
	return raw.(int), ok
}

func (h *testMetaDataHelper) Load() (int, bool) {
	if raw, ok := h.m.Load(_TestKeyType{}); ok {
		return raw.(int), true
	}
	return _IntNil, false
}

func (h *testMetaDataHelper) LoadAndDelete() (int, bool) {
	if raw, ok := h.m.LoadAndDelete(_TestKeyType{}); ok {
		return raw.(int), true
	}
	return _IntNil, false
}

func (h *testMetaDataHelper) Delete() {
	h.m.Delete(_TestKeyType{})
}
