// Code generated by "-output spiffe_id_connection_map.gen.go -type SpiffeIDConnectionMap<spiffeid.ID,*ConnectionIDSet> -output spiffe_id_connection_map.gen.go -type SpiffeIDConnectionMap<spiffeid.ID,*ConnectionIDSet>"; DO NOT EDIT.
// Install -output spiffe_id_connection_map.gen.go -type SpiffeIDConnectionMap<spiffeid.ID,*ConnectionIDSet> by "go get -u github.com/searKing/golang/tools/-output spiffe_id_connection_map.gen.go -type SpiffeIDConnectionMap<spiffeid.ID,*ConnectionIDSet>"

package spire

import (
	"github.com/spiffe/go-spiffe/v2/spiffeid"
	"sync" // Used by sync.Map.
)

// Generate code that will fail if the constants change value.
func _() {
	// An "cannot convert SpiffeIDConnectionMap literal (type SpiffeIDConnectionMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(SpiffeIDConnectionMap{})
}

var _nil_SpiffeIDConnectionMap_ConnectionIDSet_value = func() (val *ConnectionIDSet) { return }()

// Load returns the value stored in the map for a key, or nil if no
// value is present.
// The ok result indicates whether value was found in the map.
func (m *SpiffeIDConnectionMap) Load(key spiffeid.ID) (*ConnectionIDSet, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return _nil_SpiffeIDConnectionMap_ConnectionIDSet_value, ok
	}
	return value.(*ConnectionIDSet), ok
}

// Store sets the value for a key.
func (m *SpiffeIDConnectionMap) Store(key spiffeid.ID, value *ConnectionIDSet) {
	(*sync.Map)(m).Store(key, value)
}

// LoadOrStore returns the existing value for the key if present.
// Otherwise, it stores and returns the given value.
// The loaded result is true if the value was loaded, false if stored.
func (m *SpiffeIDConnectionMap) LoadOrStore(key spiffeid.ID, value *ConnectionIDSet) (*ConnectionIDSet, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return _nil_SpiffeIDConnectionMap_ConnectionIDSet_value, loaded
	}
	return actual.(*ConnectionIDSet), loaded
}

// LoadAndDelete deletes the value for a key, returning the previous value if any.
// The loaded result reports whether the key was present.
func (m *SpiffeIDConnectionMap) LoadAndDelete(key spiffeid.ID) (value *ConnectionIDSet, loaded bool) {
	actual, loaded := (*sync.Map)(m).LoadAndDelete(key)
	if actual == nil {
		return _nil_SpiffeIDConnectionMap_ConnectionIDSet_value, loaded
	}
	return actual.(*ConnectionIDSet), loaded
}

// Delete deletes the value for a key.
func (m *SpiffeIDConnectionMap) Delete(key spiffeid.ID) {
	(*sync.Map)(m).Delete(key)
}

// Range calls f sequentially for each key and value present in the map.
// If f returns false, range stops the iteration.
//
// Range does not necessarily correspond to any consistent snapshot of the Map's
// contents: no key will be visited more than once, but if the value for any key
// is stored or deleted concurrently, Range may reflect any mapping for that key
// from any point during the Range call.
//
// Range may be O(N) with the number of elements in the map even if f returns
// false after a constant number of calls.
func (m *SpiffeIDConnectionMap) Range(f func(key spiffeid.ID, value *ConnectionIDSet) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(spiffeid.ID), value.(*ConnectionIDSet))
	})
}
