// Code generated by "-output nse_registry_client_map.gen.go -type nseRegistryClientMap<string,github.com/networkservicemesh/api/pkg/api/registry.NetworkServiceEndpointRegistryClient> -output nse_registry_client_map.gen.go -type nseRegistryClientMap<string,github.com/networkservicemesh/api/pkg/api/registry.NetworkServiceEndpointRegistryClient>"; DO NOT EDIT.
package sandbox

import (
	"sync" // Used by sync.Map.

	"github.com/networkservicemesh/api/pkg/api/registry"
)

// Generate code that will fail if the constants change value.
func _() {
	// An "cannot convert nseRegistryClientMap literal (type nseRegistryClientMap) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(nseRegistryClientMap{})
}

var _nil_nseRegistryClientMap_registry_NetworkServiceEndpointRegistryClient_value = func() (val registry.NetworkServiceEndpointRegistryClient) { return }()

// Load returns the value stored in the map for a key, or nil if no
// value is present.
// The ok result indicates whether value was found in the map.
func (m *nseRegistryClientMap) Load(key string) (registry.NetworkServiceEndpointRegistryClient, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return _nil_nseRegistryClientMap_registry_NetworkServiceEndpointRegistryClient_value, ok
	}
	return value.(registry.NetworkServiceEndpointRegistryClient), ok
}

// Store sets the value for a key.
func (m *nseRegistryClientMap) Store(key string, value registry.NetworkServiceEndpointRegistryClient) {
	(*sync.Map)(m).Store(key, value)
}

// LoadOrStore returns the existing value for the key if present.
// Otherwise, it stores and returns the given value.
// The loaded result is true if the value was loaded, false if stored.
func (m *nseRegistryClientMap) LoadOrStore(key string, value registry.NetworkServiceEndpointRegistryClient) (registry.NetworkServiceEndpointRegistryClient, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return _nil_nseRegistryClientMap_registry_NetworkServiceEndpointRegistryClient_value, loaded
	}
	return actual.(registry.NetworkServiceEndpointRegistryClient), loaded
}

// LoadAndDelete deletes the value for a key, returning the previous value if any.
// The loaded result reports whether the key was present.
func (m *nseRegistryClientMap) LoadAndDelete(key string) (value registry.NetworkServiceEndpointRegistryClient, loaded bool) {
	actual, loaded := (*sync.Map)(m).LoadAndDelete(key)
	if actual == nil {
		return _nil_nseRegistryClientMap_registry_NetworkServiceEndpointRegistryClient_value, loaded
	}
	return actual.(registry.NetworkServiceEndpointRegistryClient), loaded
}

// Delete deletes the value for a key.
func (m *nseRegistryClientMap) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

// Range calls f sequentially for each key and value present in the map.
// If f returns false, range stops the iteration.
//
// Range does not necessarily correspond to any consistent snapshot of the Map's
// contents: no key will be visited more than once, but if the value for any key
// is stored or deleted concurrently, Range may reflect any mapping for that key
// from any point during the Range call.
//
// Range may be O(N) with the number of elements in the map even if f returns
// false after a constant number of calls.
func (m *nseRegistryClientMap) Range(f func(key string, value registry.NetworkServiceEndpointRegistryClient) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(registry.NetworkServiceEndpointRegistryClient))
	})
}
