// Code generated by "go-syncmap -output sync_map.gen.go -type Map<string,*net/url.URL>"; DO NOT EDIT.

package localbypass

import (
	"net/url"
	"sync"
)

func _() {
	// An "cannot convert Map literal (type Map) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(Map{})
}
func (m *Map) Store(key string, value *url.URL) {
	(*sync.Map)(m).Store(key, value)
}

func (m *Map) LoadOrStore(key string, value *url.URL) (*url.URL, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return nil, loaded
	}
	return actual.(*url.URL), loaded
}

func (m *Map) Load(key string) (*url.URL, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return nil, ok
	}
	return value.(*url.URL), ok
}

func (m *Map) Delete(key string) {
	(*sync.Map)(m).Delete(key)
}

func (m *Map) Range(f func(key string, value *url.URL) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(string), value.(*url.URL))
	})
}
