// Code generated by "go-syncmap -output sync_map.gen.go -type Map<net/url.URL,string>"; DO NOT EDIT.

package endpointurls

import (
	"net/url"
	"sync"
)

func _() {
	// An "cannot convert Map literal (type Map) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(Map{})
}

var _nil_Map_string_value = func() (val string) { return }()

func (m *Map) Store(key url.URL, value string) {
	(*sync.Map)(m).Store(key, value)
}

func (m *Map) LoadOrStore(key url.URL, value string) (string, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return _nil_Map_string_value, loaded
	}
	return actual.(string), loaded
}

func (m *Map) Load(key url.URL) (string, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return _nil_Map_string_value, ok
	}
	return value.(string), ok
}

func (m *Map) Delete(key url.URL) {
	(*sync.Map)(m).Delete(key)
}

func (m *Map) Range(f func(key url.URL, value string) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(url.URL), value.(string))
	})
}
