// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package repository

import (
	"github.com/networkservicemesh/api/pkg/api/registry"

	"github.com/networkservicemesh/sdk/pkg/tools/serialize"
)

type memoryRegistryNetworkServiceRepository struct {
	items map[string]*registry.NetworkService
	serialize.Executor
	getID func(*registry.NetworkService) string
}

func (g *memoryRegistryNetworkServiceRepository) Get(id string) *registry.NetworkService {
	var result *registry.NetworkService
	<-g.AsyncExec(func() {
		result = g.items[id]
	})
	return result
}

func (g *memoryRegistryNetworkServiceRepository) Put(item *registry.NetworkService) {
	g.AsyncExec(func() {
		g.items[g.getID(item)] = item
	})
}

func (g *memoryRegistryNetworkServiceRepository) Delete(id string) {
	g.AsyncExec(func() {
		delete(g.items, id)
	})
}

func (g *memoryRegistryNetworkServiceRepository) GetAll() []*registry.NetworkService {
	return g.GetAllByFilter(func(service *registry.NetworkService) bool {
		return true
	})
}

func (g *memoryRegistryNetworkServiceRepository) GetAllByFilter(filter func(service *registry.NetworkService) bool) []*registry.NetworkService {
	var items []*registry.NetworkService
	<-g.AsyncExec(func() {
		for _, v := range g.items {
			if filter(v) {
				items = append(items, v)
			}
		}
	})
	return items
}

// RegistryNetworkServiceRepository represents API for registry.NetworkService resources
type RegistryNetworkServiceRepository interface {
	// AsyncExec execs specific func synchronized with RegistryNetworkServiceRepository
	AsyncExec(f func()) <-chan struct{}
	// Get gets registry.NetworkService by identity
	Get(string) *registry.NetworkService
	// Put stores registry.NetworkService
	Put(*registry.NetworkService)
	// Delete deletes registry.NetworkService by identity
	Delete(string)
	// GetAll gets all RegistryNetworkServices
	GetAll() []*registry.NetworkService
	// GetAllByFilter gets all RegistryNetworkServices by specific criterion
	GetAllByFilter(func(service *registry.NetworkService) bool) []*registry.NetworkService
}

// NewRegistryNetworkServiceMemoryRepository creates new instance of RegistryNetworkServiceRepository with specific identity func
func NewRegistryNetworkServiceMemoryRepository(getID func(*registry.NetworkService) string) RegistryNetworkServiceRepository {
	return &memoryRegistryNetworkServiceRepository{
		getID: getID,
		items: map[string]*registry.NetworkService{},
	}
}
