// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package repository

import (
	"github.com/networkservicemesh/api/pkg/api/registry"
	"github.com/networkservicemesh/sdk/pkg/tools/serialize"
)

type memoryRegistryNetworkServiceEndpointRepository struct {
	items map[string]*registry.NetworkServiceEndpoint
	serialize.Executor
	getId func(*registry.NetworkServiceEndpoint) string
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Get(id string) *registry.NetworkServiceEndpoint {
	var result *registry.NetworkServiceEndpoint
	<-g.AsyncExec(func() {
		result = g.items[id]
	})
	return result
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Put(item *registry.NetworkServiceEndpoint) {
	g.AsyncExec(func() {
		g.items[g.getId(item)] = item
	})
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Delete(id string) {
	g.AsyncExec(func() {
		delete(g.items, id)
	})
}

func (g *memoryRegistryNetworkServiceEndpointRepository) GetAll() []*registry.NetworkServiceEndpoint {
	return g.GetAllByFilter(func(service *registry.NetworkServiceEndpoint) bool {
		return true
	})
}

func (g *memoryRegistryNetworkServiceEndpointRepository) GetAllByFilter(filter func(service *registry.NetworkServiceEndpoint) bool) []*registry.NetworkServiceEndpoint {
	var items []*registry.NetworkServiceEndpoint
	<-g.AsyncExec(func() {
		for _, v := range g.items {
			if filter(v) {
				items = append(items, v)
			}
		}
	})
	return items
}

type RegistryNetworkServiceEndpointRepository interface {
	AsyncExec(f func()) <-chan struct{}
	Get(string) *registry.NetworkServiceEndpoint
	Put(*registry.NetworkServiceEndpoint)
	Delete(string)
	GetAll() []*registry.NetworkServiceEndpoint
	GetAllByFilter(func(service *registry.NetworkServiceEndpoint) bool) []*registry.NetworkServiceEndpoint
}

func NewRegistryNetworkServiceEndpointMemoryRepository(getId func(*registry.NetworkServiceEndpoint) string) RegistryNetworkServiceEndpointRepository {
	return &memoryRegistryNetworkServiceEndpointRepository{
		getId: getId,
		items: map[string]*registry.NetworkServiceEndpoint{},
	}
}
