// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package repository

import (
	"github.com/networkservicemesh/api/pkg/api/registry"

	"github.com/networkservicemesh/sdk/pkg/tools/serialize"
)

type memoryRegistryNetworkServiceEndpointRepository struct {
	items map[string]*registry.NetworkServiceEndpoint
	serialize.Executor
	getID func(*registry.NetworkServiceEndpoint) string
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Get(id string) *registry.NetworkServiceEndpoint {
	var result *registry.NetworkServiceEndpoint
	<-g.AsyncExec(func() {
		result = g.items[id]
	})
	return result
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Put(item *registry.NetworkServiceEndpoint) *registry.NetworkServiceEndpoint {
	var result *registry.NetworkServiceEndpoint
	<-g.AsyncExec(func() {
		result = g.items[g.getID(item)]
		g.items[g.getID(item)] = item
	})
	return result
}

func (g *memoryRegistryNetworkServiceEndpointRepository) Delete(id string) {
	g.AsyncExec(func() {
		delete(g.items, id)
	})
}

func (g *memoryRegistryNetworkServiceEndpointRepository) GetAll() []*registry.NetworkServiceEndpoint {
	return g.GetAllByFilter(func(service *registry.NetworkServiceEndpoint) bool {
		return true
	})
}

func (g *memoryRegistryNetworkServiceEndpointRepository) GetAllByFilter(filter func(service *registry.NetworkServiceEndpoint) bool) []*registry.NetworkServiceEndpoint {
	var items []*registry.NetworkServiceEndpoint
	<-g.AsyncExec(func() {
		for _, v := range g.items {
			if filter(v) {
				items = append(items, v)
			}
		}
	})
	return items
}

// RegistryNetworkServiceEndpointRepository represents API for registry.NetworkServiceEndpoint resources
type RegistryNetworkServiceEndpointRepository interface {
	// AsyncExec execs specific func synchronized with RegistryNetworkServiceEndpointRepository
	AsyncExec(f func()) <-chan struct{}
	// Get gets registry.NetworkServiceEndpoint by identity
	Get(string) *registry.NetworkServiceEndpoint
	// Put stores registry.NetworkServiceEndpoint
	Put(*registry.NetworkServiceEndpoint) *registry.NetworkServiceEndpoint
	// Delete deletes registry.NetworkServiceEndpoint by identity
	Delete(string)
	// GetAll gets all RegistryNetworkServiceEndpoints
	GetAll() []*registry.NetworkServiceEndpoint
	// GetAllByFilter gets all RegistryNetworkServiceEndpoints by specific criterion
	GetAllByFilter(func(service *registry.NetworkServiceEndpoint) bool) []*registry.NetworkServiceEndpoint
}

// NewRegistryNetworkServiceEndpointMemoryRepository creates new instance of RegistryNetworkServiceEndpointRepository with specific identity func
func NewRegistryNetworkServiceEndpointMemoryRepository(getID func(*registry.NetworkServiceEndpoint) string) RegistryNetworkServiceEndpointRepository {
	return &memoryRegistryNetworkServiceEndpointRepository{
		getID: getID,
		items: map[string]*registry.NetworkServiceEndpoint{},
	}
}
