// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) 2020 Doc.ai and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package repository

import (
	"github.com/networkservicemesh/api/pkg/api/registry"
	"github.com/networkservicemesh/sdk/pkg/tools/serialize"
)

type memoryRegistryNetworkServiceManagerRepository struct {
	items map[string]*registry.NetworkServiceManager
	serialize.Executor
	getId func(*registry.NetworkServiceManager) string
}

func (g *memoryRegistryNetworkServiceManagerRepository) Get(id string) *registry.NetworkServiceManager {
	var result *registry.NetworkServiceManager
	<-g.AsyncExec(func() {
		result = g.items[id]
	})
	return result
}

func (g *memoryRegistryNetworkServiceManagerRepository) Put(item *registry.NetworkServiceManager) {
	<-g.AsyncExec(func() {
		g.items[g.getId(item)] = item
	})
}

func (g *memoryRegistryNetworkServiceManagerRepository) Delete(id string) {
	<-g.AsyncExec(func() {
		delete(g.items, id)
	})
}

func (g *memoryRegistryNetworkServiceManagerRepository) GetAll() []*registry.NetworkServiceManager {
	return g.GetAllByFilter(func(service *registry.NetworkServiceManager) bool {
		return true
	})
}

func (g *memoryRegistryNetworkServiceManagerRepository) GetAllByFilter(filter func(service *registry.NetworkServiceManager) bool) []*registry.NetworkServiceManager {
	var items []*registry.NetworkServiceManager
	<-g.AsyncExec(func() {
		for _, v := range g.items {
			if filter(v) {
				items = append(items, v)
			}
		}
	})
	return items
}

type RegistryNetworkServiceManagerRepository interface {
	AsyncExec(f func()) <-chan struct{}
	Get(string) *registry.NetworkServiceManager
	Put(*registry.NetworkServiceManager)
	Delete(string)
	GetAll() []*registry.NetworkServiceManager
	GetAllByFilter(func(service *registry.NetworkServiceManager) bool) []*registry.NetworkServiceManager
}

func NewRegistryNetworkServiceManagerMemoryRepository(getId func(*registry.NetworkServiceManager) string) RegistryNetworkServiceManagerRepository {
	return &memoryRegistryNetworkServiceManagerRepository{
		getId: getId,
		items: map[string]*registry.NetworkServiceManager{},
	}
}
